### ISSUE TITLE
Add setCity() and setState() methods

### ISSUE THREAD

**Issue by karllhughes** [JobBrander/jobs-authenticjobs#2]
Reasons outlined in pull request #1

**Comment by stevenmaguire** [comment]
@karllhughes I've removed the setLocation and added a blended setCity and setState (they would compete with each other, otherwise). Please review the commit here: https://github.com/JobBrander/jobs-authenticjobs/commit/515da19d5247d4338d4dde52f387ed3d29a68b5a

I am sensitive to the need for the API to remain as consistent as possible across all providers, however this will not be possible given the edge cases that we may need to support from time to time. For instance, in this particular case the setSort method for this provider will only respond successfully with provider specific entry, so the hope that a common API with setSort across all providers, while consistent, will not provider "hot swapping" of providers. 

I think it would be a good idea to move this discussion to the common project and decide on a minimum set of "consistent" setters that each provider MUST implement, and provide no conflicts, then add them appropriate abstract methods to the AbstractProvider. In order to achieve this decision, I'd like to understand more clearly the use case you're encountering that highlights these differences.
